-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 07, 2021 at 03:14 PM
-- Server version: 10.4.19-MariaDB
-- PHP Version: 7.4.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sampledb`
--

-- --------------------------------------------------------

--
-- Table structure for table `chatbot`
--

CREATE TABLE `chatbot` (
  `id` int(11) NOT NULL,
  `user_question` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
  `bot_reply` text CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `chatbot`
--

INSERT INTO `chatbot` (`id`, `user_question`, `bot_reply`) VALUES
(1, 'hii||hello||namasthe||Hii||Hello||Namasthe', 'Namasthe.<br>\r\n<br>\r\nThis is Covid-19 chatbot for Andhra Pradesh to  create awareness on corona and help you and your family stay safe.<br>\r\n<br>\r\nI will help you to find about the info of:-<br> \r\n<br>\r\n1.Vaccination hospitals&Availability of Oxygen beds<br>\r\n<br>\r\n2.Precautions to fight against coronavirus <br>\r\n<br>\r\n3.Syptoms of coronavirus<br>\r\n<br>\r\n4.Vaccines'),
(2, '1\r\n', 'Please enter the district:-<br>\r\nAnantapur<br>\r\nChittor<br>\r\nEast Godavari<br>\r\nGuntur<br>\r\nKadapa<br>\r\nKrishna<br>\r\nKurnool<br>\r\nNellore<br>\r\nPrakasham<br>\r\nSrikakulam<br>\r\nVisakhapatnam<br>\r\nVizianagaram<br>\r\nWest Godavari<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the menu page or say \"Thank you\" to quit from the bot'),
(3, 'Anantapur', 'These are the vaccination&oxygen beds availbility hospitals in Ananthapur:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name: Pavani Multi Speciality <br>\r\n  Category : Private<br> \r\n  Type : Paid<br> \r\n  Address: D.No. 12-3-195,5th Cross,Sai \r\n  Nagar,Anantapur<br>\r\n  Contact: 085542 45333 <br>\r\n<br>\r\n2.Hospital Name: Sainath Hospital<br>\r\n  Category : Private <br>\r\n  Type : Paid<br>\r\n  Address: 1-616-2B,R.S.ROAD,KADIRI<br>\r\n  Contact: 084942 23496<br> \r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:Saveera Hospital <br>\r\n  Arogyasri status:Partially <br>\r\n  Available Oxygen beds:16 <br>\r\n  Address:1348, Opp Sakshi Office,NH 44, \r\n  Anantapur<br>\r\n  Contact:  099663 12345<br>\r\n<br>\r\n2.Hospital Name:AH, Kadiri<br>\r\n  Arogyasri status:Government<br>\r\n  Available Oxygen beds:31 <br>\r\n  Address:Main Rd, Revenue Colony, Kadiri\r\n<br>\r\n  Contact:08494223595 <br>\r\n<br>\r\n<br> \r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(4, 'Chittor', 'These are the vaccination&oxygen beds availability hospitals in chittor:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:Apollo Hospitals <br>\r\nCategory : Private<br>\r\nType: Paid <br>\r\nAddress:ARAGONDA,THAVANAMPALLI (M),CHITTOOR\r\n<br>\r\nContact:  085732 83221<br>\r\n<br>\r\n2.Hospital Name:NEPHROPLUS <br>\r\n Category : Public <br>\r\nType: Free <br>\r\nAddress:GOVT.GENRAL HOSPITAL ALIPIRI Road,Tirupathi <br>\r\n Contact: 0877 222 2867  <br>\r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:Lotus Hospital<br>\r\nArogyasri status:Partially <br>\r\n Available Oxygen beds: 15 <br>\r\nAddress:Chittor<br>\r\nContact:8772252962 <br>\r\n<br>\r\n2.Hospital Name:SVRRGG Hospital<br>\r\nArogyasri status: Government<br>\r\nAvailable Oxygen beds: 252<br>\r\nAddress:Alipiri Rd,Tirupati<br>\r\nContact: 0877 222 2867<br>\r\n<br>\r\n<br>\r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot\r\n'),
(5, 'East Godavari', 'These are the vaccination&oxygen beds availability hospitals in East Godavari:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:Royal Hospital <br>\r\nCategory : Private<br>\r\nType: Paid <br>\r\nAddress:20-23-4,Aryapuram,Behind Nagadevi Theatre,Rajahmundry  \r\n<br>\r\n Contact: 094907 41382 <br>\r\n<br>\r\n2.Hospital Name:NEPHROPLUS <br>\r\n Category : Public <br>\r\nType: Free <br>\r\nAddress:GOVERNMENT GENRAL HOSPITAL,GGH ROAD,RRROAD,KAKINADA<br>\r\n Contact:NA <br>\r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:TEAM HOSPITAL<br>\r\nArogyasri status:Private <br>\r\n Available Oxygen beds: 19 <br>\r\nAddress:behind Ashram Public school, Nagamalli Thota,Kakinada<br>\r\nContact:08842356002 <br>\r\n<br>\r\n2.Hospital Name:District Hospital<br>\r\nArogyasri status: Government<br>\r\nAvailable Oxygen beds: 175<br>\r\nAddress:Police Quarters, Padmavathi Nagar,Rajahmundry<br>\r\nContact:08832951177<br>\r\n<br>\r\n<br>\r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(6, 'Guntur', 'These are the vaccination&oxygen beds availability hospitals in Guntur:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:FARZANA HOSPITALS <br>\r\nCategory : Private<br>\r\nType: Paid <br>\r\nAddress:16-3-12/3,NIMMATHOTA,NARSARAOPET,\r\nGuntur \r\n<br>\r\n Contact:NA <br>\r\n<br>\r\n2.Hospital Name:NEPHROPLUS <br>\r\n Category : Public <br>\r\nType: Free <br>\r\nAddress:WARD NO 116,RAILWAY STATION ROAD, SAMBASIVAPET,GUNTUR<br>\r\n Contact:NA <br>\r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:Amaravathi Hospital<br>\r\nArogyasri status:Partially  <br>\r\n  Available Oxygen beds: 33  <br>\r\nAddress:Old Club Rd, Gunturvari Thota, Kothapeta, Guntur<br>\r\nContact:08632256699   <br>\r\n<br>\r\n2.Hospital Name:GGH,GUNTUR<br>\r\nArogyasri status: Government<br>\r\n Available Oxygen beds: 100	<br>\r\nAddress:Sambasiva Pet, Guntur                                    <br>\r\nContact:9494520370<br>\r\n<br>\r\n<br>\r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(7, 'Kadapa', 'These are the vaccination&oxygen beds availibility hospitals in Kadapa:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name: NANDIKA HOSPITAL<br>\r\n  Category : Private<br> \r\n  Type : Paid<br> \r\n  Address:4-14-44-8 <br>\r\n    Contact:NA    <br>\r\n<br>\r\n2.Hospital Name:TEJA HOSPITAL<br>\r\n  Category : Private <br>\r\n  Type : Paid<br>\r\n Address:4/596<br>\r\n   Contact:NA<br> \r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:KVR MULTI SPECIALITY <br>\r\n  Arogyasri status:Partially <br>\r\n  Available Oxygen beds: 17  <br>\r\n  Address:Beside Superbazar Road,Gandhi \r\n  Road, PRODDATUR<br>\r\n  Contact:7207155004 <br>\r\n<br>\r\n2.Hospital Name:DH Proddutur<br>\r\n  Arogyasri status:Government<br>\r\n  Available Oxygen beds: 45  <br>\r\n  Address: Dastagiripet 2, Nadimpalli, \r\n  Proddatur<br>\r\n  Contact:08564245255 <br>\r\n<br>\r\n<br> \r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(8, 'Krishna', 'These are the vaccination&oxygen beds availibility hospitals in Krishna:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:SUNRISE HOSPITALS<br>\r\n  Category : Private<br> \r\n  Type : Paid<br> \r\n  Address:33-25-35 <br>\r\n  Contact: 0866 243 4646<br>\r\n<br>\r\n2.Hospital Name:MARTHA HEALTH CARE<br>\r\n  Category : Private <br>\r\n  Type : Paid<br>\r\n Address:16-99-3,ASHOK NAGAR,TIRUVURU<br>\r\n   Contact:NA<br> \r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:Pinnamaneni Hospital <br>\r\n  Arogyasri status:Partially <br>\r\n Available Oxygen beds: 100 <br>\r\nAddress:Chinna Avutapalli,Peda Avutapalli <br>\r\n  Contact:08676257223<br>\r\n<br>\r\n2.Hospital Name:GGH,Vijayawada<br>\r\n  Arogyasri status:Government<br>\r\n   Available Oxygen beds: 125 <br>\r\n  Address:NH 16 Service Rd, Beside NTR Health University, Gunadala, Vijayawada\r\n<br>\r\n   Contact:08662457789<br>\r\n<br>\r\n<br> \r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(9, 'Kurnool', 'These are the vaccination&oxygen beds availibility hospitals in Kurnool:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:Shantiram Medical College <br>\r\n  Category : Private<br> \r\n  Type : Paid<br> \r\n Address:NH-18,NandyalKurnool<br>\r\n   Contact:NA <br>\r\n<br>\r\n2.Hospital Name:SANJEEVANI HEALTH CARE\r\n<br>\r\n  Category : Private <br>\r\n  Type : Paid<br>\r\n Address:201/2A2,MAMIDALAPADU,KURNOOL<br>\r\n Contact: 085182 26463<br> \r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:Ameelio Hospitals <br>\r\n  Arogyasri status:Partially <br>\r\n Available Oxygen beds: 62<br>\r\n Address:Guru Raghavendra Nagar,Kurnool <br>\r\n Contact:7207082844<br>\r\n<br>\r\n2.Hospital Name:Area Hospital<br>\r\n  Arogyasri status:Government<br>\r\n  Available Oxygen beds: 54 <br>\r\n  Address:Old Town, Adoni<br>\r\n  Contact:08512295796 <br>\r\n<br>\r\n<br> \r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(10, 'Nellore', 'These are the vaccination&oxygen beds availibility hospitals in Nellore:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:KIMS Bollineni <br>\r\n  Category : Private<br> \r\n  Type : Paid<br> \r\n  Address:DARGAMITTA,NELLORE<br>\r\n  Contact:0861 231 5835  <br>\r\n<br>\r\n2.Hospital Name:NEPHROPLUS<br>\r\n  Category : Public  <br>\r\n  Type : Free <br>\r\n  Address:ACR medicalcollege, Nellore<br>\r\n  Contact:NA <br> \r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:NARAYANA MEDICAL HOSPITAL <br>\r\n   Arogyasri status:Arogyasri   <br>\r\n  Available Oxygen beds: 90 <br>\r\n  Address:Chintareddy Palem, Nellore<br>\r\n  Contact:08612350554<br>\r\n<br>\r\n2.Hospital Name:Govt General Hospital<br>\r\n  Arogyasri status:Government<br>\r\n  Available Oxygen beds: 475 <br>\r\n Address:GNT Rd, Dargamitta, Nellore\r\n<br>\r\n Contact:08612330026<br>\r\n<br>\r\n<br> \r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(11, 'Prakasham', 'These are the vaccination&oxygen beds availibility hospitals in Prakasham:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:KAKUMANI HOSPITAL <br>\r\n  Category : Private<br> \r\n  Type : Paid<br> \r\n Address:37-1-5-17<br>\r\n  Contact: 085922 22022 <br>\r\n<br>\r\n2.Hospital Name:NEPHROPLUS<br>\r\n  Category :Public   <br>\r\n  Type : Free<br>\r\n  Address:Rims,Bhagyanagar,Ongole,5th lane<br>\r\n  Contact:NA <br> \r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:ZACHARAIAH HOSPITAL <br>\r\n  Arogyasri status: Private <br>\r\n  Available Oxygen beds: 20 <br>\r\n  Address:D.No: 35-3-72, Zachariah Nagar, \r\n  Ongole <br>\r\n Contact:9966838306  <br>\r\n<br>\r\n2.Hospital Name:GGH<br>\r\n  Arogyasri status:Government<br>\r\n   Available Oxygen beds: 217 <br>\r\n Address: Gopal Nagar 5th Ln,Bhagyanagar, \r\n  Ongole<br>\r\n  Contact:08592233270   <br>\r\n<br>\r\n<br> \r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(12, 'Srikakulam', 'These are the vaccination&oxygen beds availibility hospitals in Srikakulam:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:AMRUTHA HOSPITAL<br>\r\n  Category : Private<br> \r\n  Type : Paid<br> \r\n  Address:6-615<br>\r\n   Contact:NA <br>\r\n<br>\r\n2.Hospital Name:NEPHROPLUS<br>\r\n  Category :Public <br>\r\n  Type : Free <br>\r\n  Address:RIMS,BALAGA,SRIKAKAULAM<br>\r\n  Contact:NA<br> \r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:Sindhura <br>\r\n  Arogyasri status:Partially <br>\r\n  Available Oxygen beds: 9 <br>\r\n  Address:NEW BRIDGE ROAD, Srikakulam<br>\r\n  Contact:08942-228455<br>\r\n<br>\r\n2.Hospital Name:RIMS HOSPITAL<br>\r\n  Arogyasri status:Government<br>\r\n Available Oxygen beds: 144 <br>\r\n Address:Hudco Colony, Balaga, Srikakulam\r\n<br>\r\n  Contact:08942279214 <br>\r\n<br>\r\n<br> \r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(13, 'Visakhapatnam', 'These are the vaccination&oxygen beds availibility hospitals in Visakhapatnam:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:Care Hospital <br>\r\n  Category : Private<br> \r\n  Type : Paid<br> \r\n  Address:MAIN ROAD, VIZAG<br>\r\n   Contact:0891 616 5656<br>\r\n<br>\r\n2.Hospital Name:Padmaja Hospital<br>\r\n  Category : Private <br>\r\n  Type : Paid<br>\r\n  Address:OLD GAJUWAKA JUNCTION, \r\n  VISAKHAPATNAM<br>\r\n  Contact:089125 15648<br> \r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:Apollo hospital <br>\r\n  Arogyasri status: Private <br>\r\n  Available Oxygen beds: 84 <br>\r\nAddress: Health City, Arilova, Chinagadila<br>\r\n Contact:0891-2867777<br>\r\n<br>\r\n2.Hospital Name:Govt Hospital<br>\r\n  Arogyasri status:Government<br>\r\n  Available Oxygen beds: 200 <br>\r\n  Address: Chinna Waltair, Pedda Waltair,\r\nVisakhapatnam<br>\r\n  Contact:9392307880 <br>\r\n<br>\r\n<br> \r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(14, 'Vizianagaram', 'These are the vaccination&oxygen beds availibility hospitals in Vizianagaram:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:MARUTHI HOSPITAL<br>\r\n  Category : Private<br> \r\n  Type : Paid<br> \r\n  Address:22-87<br>\r\n   Contact:NA<br>\r\n<br>\r\n2.Hospital Name:NEPHROPLUS<br>\r\n  Category :Public <br>\r\n  Type : Free <br>\r\n  Address:VIZIANAGARAM <br>\r\n  Contact:NA<br> \r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:MIMS<br>\r\n  Arogyasri status:Partially <br>\r\n   Available Oxygen beds: 110 <br>\r\n Address:31-15, near MDO Office, \r\n  Nellimarla <br>\r\n  Contact:08922 244666<br>\r\n<br>\r\n2.Hospital Name:AREA HOSPITAL<br>\r\n  Arogyasri status:Government<br>\r\n  Available Oxygen beds: 17 <br>\r\n  Address:Vizianagaram<br>\r\n  Contact:08963222098 <br>\r\n<br>\r\n<br> \r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(15, 'West Godavari', 'These are the vaccination&oxygen beds availibility hospitals in West Godavari:-<br>\r\n<br>\r\nVaccination Hospitals:<br>\r\n<br>\r\n1.Hospital Name:VIJAYA HOSPITALS <br>\r\n  Category : Private<br> \r\n  Type : Paid<br> \r\n  Address:23A-6-63/2  <br>\r\n   Contact: 088122 30500  <br>\r\n<br>\r\n2.Hospital Name:NEPHROPLUS <br>\r\n  Category :Public<br>\r\n  Type : Free <br>\r\n Address:ELURU<br>                  Contact: 088122 30401<br> \r\n<br>\r\n<br>\r\n***For more information,please refer this link \"https://pmjay.gov.in/sites/default/files/2021-02/PMJAY_empanelled_hospitals_0.pdf\"<br>\r\n<br>\r\nOxygen beds availability hospitals:<br>\r\n<br>\r\n1.Hospital Name:Ashram <br>\r\n  Arogyasri status:Partially <br>\r\n Available Oxygen beds: 151<br>\r\n  Address:NH 5, Asram Road<br>\r\n  Contact:08812288288 <br>\r\n<br>\r\n2.Hospital Name:DISTRICT HOSPITAL<br>\r\n  Arogyasri status:Government<br>\r\n  Available Oxygen beds: 81  <br>\r\n  Address:Islampet, Eluru<br>\r\n  Contact:8466015130 <br>\r\n<br>\r\n<br> \r\n***For Furthur updates,please refer this link \"http://dashboard.covid19.ap.gov.in/ims/hospbed_reports/\"<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(16, 'Menu', 'Namasthe.<br>\r\n<br>\r\nThis is Covid-19 chatbot for Andhra Pradesh to  create awareness on corona and help you and your family stay safe.<br>\r\n<br>\r\nI will help you to find about the info of:-<br> \r\n<br>\r\n1.Vaccination hospitals&Availability of Oxygen beds<br>\r\n<br>\r\n2.Precautions to fight against coronavirus <br>\r\n<br>\r\n3.Syptoms of coronavirus<br>\r\n<br>\r\n4.Vaccines'),
(17, 'Thank you', 'You are always welcome!'),
(18, '2', 'Follow below precautions to keep yourself and your loved ones safe from covid-19:-<br>\r\n<br>\r\n---> Wear a mask: Wear a well-fitting three-layer mask, especially when you can’t physically distance,or if you’re indoors. Clean your hands before putting on and taking off a mask.<br>\r\n<br>\r\n--->Keep your distance: Stay at least 1 metre away from others, even if they don’t appear to be sick,since people can have the virus without having symptoms.<br>\r\n<br>\r\n--->Follow local guidance: Check to see what national, regional and local authorities are advising so you have the most relevant information for where you are.<br>\r\n<br>\r\n--->Avoid crowded places, poorly ventilated, indoor locations and avoid prolonged contact with others. Spend more time outdoors than indoors.<br>\r\n<br>\r\n--->Ventilation is important: Open windows when indoors to increase the amount of outdoor air.<br>\r\n<br>\r\n--->Avoid touching surfaces, especially in public settings or health facilities, in case people infected with COVID-19 have touched them. Clean surfaces regularly with standard disinfectants.<br>\r\n<br>\r\n--->Frequently clean your hands with soap and water, or an alcohol-based hand rub.If you can, carry alcohol-based rub with you and use it often.<br>\r\n<br>\r\n--->Cover your coughs and sneezes with a bent elbow or tissue, throwing used tissues into a closed bin right away. Then wash your hands or use an alcohol-based hand rub.<br>\r\n<br>\r\n--->Get vaccinated: When it’s your turn, get vaccinated. Follow local guidance and recommendations about vaccination.<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(19, '3', 'Symptoms  of corona virus:-<br>\r\n--|--Most common symptoms:<br>\r\n<br>\r\n--->fever<br>\r\n<br>\r\n--->dry cough<br>\r\n<br>\r\n--->tiredness<br>\r\n<br>\r\n<br>\r\n--|--Less common symptoms:<br>\r\n<br>\r\n--->aches and pains<br>\r\n<br>\r\n--->sore throat<br>\r\n<br>\r\n--->diarrhoea<br>\r\n<br>\r\n--->conjunctivitis<br>\r\n<br>\r\n--->headache<br>\r\n<br>\r\n--->loss of taste or smell<br>\r\n<br>\r\n--->a rash on skin, or discolouration of fingers or toes<br>\r\n<br>\r\n<br>\r\n--|--Serious symptoms:<br>\r\n<br>\r\n--->difficulty breathing or shortness of breath<br>\r\n<br>\r\n--->chest pain or pressure<br>\r\n<br>\r\n--->loss of speech or movement<br>\r\n<br>\r\n<br>\r\n***Seek immediate medical attention if you have serious symptoms. Always call before visiting your doctor or health facility.<br>\r\n<br>\r\n***On average it takes 5–6 days from when someone is infected with the virus for symptoms to show, however it can take up to 14 days.<br>\r\n<br>\r\n***People with mild symptoms who are otherwise healthy should manage their symptoms at home<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot'),
(20, '4', 'Present there are mainly three types of vaccines running in India:-<br>\r\n1.Covaxin:-<br>\r\n<br>\r\n           Covaxin is a COVID-19 vaccine developed by Bharat Biotech, an Indian biotechnology company,and the Indian Council of Medical Research.<br>\r\n<br>\r\n           It is a two-dose vaccine with an efficacy rate of 78%,according to interim phase 3 clinical data.<br>\r\n<br>\r\n           Covaxin, also known as BBV152, is a type of whole-virus vaccine called an inactivated vaccine.An inactivated vaccine incorporates a modified or dead version of the virus,in this case SARS-CoV-2, which cannot replicate and so cannot cause disease.<br>\r\n<br>\r\nSide Effects:-<br>\r\n           1.fever<br>\r\n           2.headaches<br>\r\n           3.irritability<br>\r\n           4.pain, swelling, or both at the site of injection<br>\r\n<br>\r\n2.Covishield:-<br>\r\n<br>\r\n           The Covishield vaccine is a vaccine that aims to protect against COVID-19.<br>\r\n<br>\r\n           It is developed by Oxford University and AstraZeneca.<br>\r\n<br>\r\n           It is given by Intramuscular Injection,using as a vector the modified chimpanzee Adenovirus ChAdOx1.<br>\r\n<br>\r\n<br>\r\nSide Effects:-<br>\r\n           1.Pain or tenderness at the injection site<br>\r\n           2.Headache<br>\r\n           3.Tiredness<br>\r\n           4.Muscle or joint aches<br>\r\n           5.Fever<br>\r\n           6.Chills<br>\r\n           7.Nausea<br>\r\n<br>\r\n3.Sputnik-V:<br>\r\n<br>\r\n            Sputnik V is a two-dose Covid-19 vaccine, which has an efficacy of over 91 per cent, according to a publication in scientific journal The Lancet.<br>\r\n<br>\r\n            Made by the Gamaleya Research Institute of Epidemiology and Microbiology in Moscow.<br>\r\n<br>\r\n            However, unlike Covishield, which uses a weakened common cold “adenovirus” that affects chimpanzees, Sputnik V makes use of two different human adenoviruses.<br>\r\n<br>\r\n<br>\r\nSide Effects:<br>\r\n            1.flu-like illness<br>\r\n            2.headache<br>\r\n            3.fatigue<br>\r\n            4.injection-site reactions<br>\r\n<br>\r\n<br>\r\n***Type \"Menu\" to go to the home page or say \"Thank you\" to quit from the bot');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `chatbot`
--
ALTER TABLE `chatbot`
  ADD PRIMARY KEY (`id`) USING BTREE;

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `chatbot`
--
ALTER TABLE `chatbot`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
